.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH TONICDNSCLI 1 "April 19, 2012"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
tonicdnscli \- Command line client tool for TonicDNS
.SH SYNOPSIS
.B tonicdnscli
.RI [ options ] " sub-command"
.RI [ sub-cmd-options ] " [infile]"
.br
.SH DESCRIPTION
This manual page documents briefly the
.B tonicdnscli
commands.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBtonicdnscli\fP is a program that command line tool for TonicDNS API.
TonicDNS is  RESTful API for PowerDNS.
Convert readble text record to JSON, and create or delete zone records with TonicDNS.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show program's version number.
.TP
.B \-\-config CONFIG
Specify config file path.
.SH SUB COMMANDS
.B show
Print json format.
.TP
.B get
Retrieve records.
.TP
.B create
Create record.
.TP
.B bulk_create
Create bulk records.
.TP
.B delete
Delete record.
.TP
.B bulk_delete
Delete bulk records.
.TP
.B tmpl_get
Retrieve template(s).
.TP
.B tmpl_create_update
Create or update template.
.TP
.B tmpl_delete
Delete template.
.TP
.B soa
Update SOA record.

.SH INFILE
One record per one line with delimiter of space or tab.

.SH SUB COMMAND OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-s (hostname|IP address)
Specify TonicDNS server. When not `get' command only.
.TP
.B \-u USERNAME
Specify TonicDNS username.
.TP
.B \-d DOMAIN
Specify zone domain.
.TP
.B \-P | \-p PASSWORD
Specify TonicDNS password.
.TP
.B \-\-search keyword
search keyword from retrieve records with partial match word. When `get' command only.
.TP
.B \-\-name NAME
specify record name with domain option.
.TP
.B \-\-rtype TYPE
specify record type with domain option.
.TP
.B \-\-content CONTENT
specify record content with domain option.
.TP
.B \-\-ttl TTL
specify record TTL with domain option.
.TP
.B \-\-priority PRIORITY
specify record priority with domain option.
.TP
.B \-\-template TEMPLATE
specify template identifier with template option.
.TP
.B \-\-dnsaddr DNSADDR
specify TonicDNS server IP address with template option.
.TP
.B \-\-desc DESC
specify template description with template option.
.TP
.SH SEE ALSO
.br
The programs are documented fully by
.IR "README" ,
available via the Info system.
.SH AUTHOR
tonicdnscli was written by Kouhei Maeda <mkouhei@palmtb.net>.
.PP
This manual page was written by Kouhei Maeda <mkouhei@palmtb.net>,
for the Debian project (and may be used by others).
